version: '3'
services:
    web:
        image: nginx:latest
        container_name: e3t-nginx
        entrypoint: ''
        ports:
            - "80:80"
        volumes:
            - ./nginx-docker.conf:/etc/nginx/nginx.conf
            - ./html:/var/www/E3T/html
            - ./images:/var/www/E3T/images
        depends_on:
            - php
    php:
        image: php:fpm
        container_name: e3t-php
        entrypoint: ''
        volumes:
            - ./html:/var/www/E3T/html
